# Ejercicio 5: Espacio Vectorial

Implementación de un Sistema de Recuperación de Información con:

1. Carga del corpus desde Kaggle
2. Preprocesamiento
3. Recuperación con TF-IDF
4. Recuperación con BM25
5. Comparación de resultados

# Parte 0: Carga del Corpus
### Actividad

Carga el corpus   
Realiza las etapas de preprocesamiento sobre el corpus

## 1. Instalación de dependencias

In [1]:
!pip install kaggle pandas nltk scikit-learn rank-bm25

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\labp5e004\appdata\roaming\python\python313\site-packages (2.1.2)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: rank-bm25 in c:\users\labp5e004\appdata\roaming\python\python313\site-packages (0.2.2)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\labp5e004\appdata\roaming\python\python313\site-packages (from kaggle) (1.19.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.23 in c:\users\labp5e004\appdata\roaming\python\python313\site-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\programdata\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\programdata\anaconda3\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: scipy>=1.8.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: markdown-it-py>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: text-unidecode>=1.3 in c:\programdata\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->kaggle) (2025.11.12)

## 2. Importación de librerías

In [2]:
import os
import re
import zipfile
import pandas as pd
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from rank_bm25 import BM25Okapi

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# 2. Cargar el cvs

In [ ]:
import pandas as pd

# Cargar el archivo CSV y guardarlo en un datagrama
df = pd.read_csv("wikipedia_text_corpus.csv")

# Ver las primeras filas
df.head()

   Unnamed: 0                                               text
0           1  Anovo\n\nAnovo (formerly A Novo) is a computer...
1           2  Battery indicator\n\nA battery indicator (also...
2           3  Bob Pease\n\nRobert Allen Pease (August 22, 19...
3           4  CAVNET\n\nCAVNET was a secure military forum w...
4           5  CLidar\n\nThe CLidar is a scientific instrumen...

In [ ]:
# Descargar los recursos necesarios de NLTK

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LabP5E004\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
import re
from nltk.corpus import stopwords
# Eliminamos las palabras mas comunes en ingles.
stop_words = set(stopwords.words('english'))

# Creamos la funcion para tokenizar.
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', ' ', text) # Eliminamos los caracteres especiales
    tokens = text.split()   # Tokenización simple
    tokens = [t for t in tokens if t not in stop_words and len(t) > 2]
    return ' '.join(tokens)

In [9]:
processed_docs = [preprocess(doc) for doc in documents]
print("Preprocesamiento completado.")

Preprocesamiento completado.

# Parte 1: Recuperación con TF-IDF
### Actividad:

Obtén la representación vectorial de los documentos utilizando el modelo TF-IDF   
A partir de un conjunto de 10 queries, verifica la recuperación del sistema

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# 1. Crear la matriz TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(processed_docs)

print("Matriz TF-IDF creada.")
print("Dimensiones:", tfidf_matrix.shape)

# 2. Definimos las 10 consultas queries
queries = [
    "artificial intelligence",
#    "machine learning",
#    "computer networks",
#    "operating systems",
    "database systems",
    "cyber security",
    "probability and statistics",
    "software engineering",
    "data structures",
    "java programming",
    "computerized analog",
    "biological treatment",
    "Customer knowledge"

]

Matriz TF-IDF creada.
Dimensiones: (5000, 84633)

In [ ]:
# 3. Función de búsqueda
def search_tfidf(query, top_k=5):
    query_processed = preprocess(query)
    query_vector = vectorizer.transform([query_processed])

    similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[::-1][:top_k]

    # 
    results = []
    for idx in top_indices:
        results.append({
            "documento": idx,
            "score": similarities[idx],
            "texto": documents[idx][:200]
        })

    return pd.DataFrame(results)

In [20]:
# 4. Probar las 10 consultas
tfidf_results = {}

for query in queries:
    print("=" * 80)
    print("QUERY:", query)
    result = search_tfidf(query)
    tfidf_results[query] = result
    display(result)

================================================================================
QUERY: artificial intelligence

   documento     score                                              texto
0       3905  0.470889  Accounting intelligence\n\nA specialist form o...
1       4563  0.456732  Intelligence engine\n\nAn intelligence engine ...
2        669  0.403018  Open Letter on Artificial Intelligence\n\nIn J...
3       2618  0.352794  Artificial general intelligence\n\nArtificial ...
4        485  0.342451  Strategic Computing Initiative\n\nThe United S...

================================================================================
QUERY: operating systems

   documento     score                                              texto
0       3532  0.595812  List of operating systems\n\nThis is a list of...
1       4955  0.270599  Embedded system\n\nAn embedded system is a pro...
2        174  0.260313  Information system\n\nInformation systems (IS)...
3       1687  0.231710  ACM SIGOPS\n\nACM SIGOPS is the Association fo...
4       3578  0.215268  Improvement Support Systems\n\nImprovement Sup...

================================================================================
QUERY: database systems

   documento     score                                              texto
0       1158  0.358494  Integrated manufacturing database\n\nAn integr...
1       2577  0.332854  EDA database\n\nAn EDA database is a database ...
2       2963  0.325403  Aerodrome mapping database\n\nAn aerodrome map...
3       2060  0.321675  Operational database\n\nOperational database m...
4       4410  0.293588  DBMaestro\n\nDBmaestro is computer software se...

================================================================================
QUERY: cyber security

   documento     score                                              texto
0       2924  0.737210  Cyber electronic warfare\n\nCyber electronic w...
1       4258  0.504502  Cyber-physical system\n\nA cyber-physical (als...
2        699  0.452617  Cyber manufacturing\n\nCybermanufacturing is a...
3       3947  0.301217  United Nations Department for Safety and Secur...
4       3841  0.230158  Michael Gregg\n\nMichael Gregg is an American ...

================================================================================
QUERY: probability and statistics

   documento     score                                              texto
0       3799  0.172474  Stochastic neural analog reinforcement calcula...
1       2296  0.159211  K-distribution\n\nIn probability and statistic...
2       3709  0.146096  Arnold Allen\n\nArnold Oral Allen was an Ameri...
3       3138  0.109729  Local information systems\n\nA Local informati...
4       2493  0.097600  List of telecommunications regulatory bodies\n...

================================================================================
QUERY: software engineering

   documento     score                                              texto
0       4982  0.550401  Software\n\nComputer software, or simply softw...
1        193  0.536072  Software diagnosis\n\nSoftware diagnosis (also...
2        824  0.492164  Software development\n\nSoftware development i...
3       1477  0.484474  Software analyst\n\nIn a software development ...
4        711  0.427635  Mechanical engineering\n\nMechanical engineeri...

================================================================================
QUERY: data structures

   documento     score                                              texto
0       1700  0.413209  Data warehouse\n\nIn computing, a data warehou...
1       4604  0.342241  Data plan\n\nData plan refers to data quotas f...
2       3616  0.314205  Disparate system\n\nIn information technology,...
3        521  0.288603  Modular data center\n\nA modular data center s...
4       1892  0.275753  Data stream mining\n\nData Stream Mining is th...

================================================================================
QUERY: java programming

   documento     score                                              texto
0       4473  0.494693  Real time Java\n\nReal time Java is a catch-al...
1       2169  0.331344  Psychology of programming\n\nThe psychology of...
2        613  0.283718  List of programming languages\n\nThe aim of th...
3        465  0.281477  IGeoSIT\n\niGeoSIT, the Interim Geo-Spatial In...
4       2513  0.254399  Skeleton (computer programming)\n\nSkeleton pr...

================================================================================
QUERY: computerized analog

   documento     score                                              texto
0       1001  0.267137  Digital television transition\n\nThe digital t...
1       3578  0.202765  Improvement Support Systems\n\nImprovement Sup...
2        641  0.186352  Analog forestry\n\nAnalog forestry is an appro...
3       1446  0.180060  Digital-to-analog converter\n\nIn electronics,...
4       2544  0.174426  Jim Williams (analog designer)\n\nJames M. Wil...

================================================================================
QUERY: biological treatment

   documento     score                                              texto
0       3504  0.472917  Waste treatment\n\nWaste treatment refers to t...
1       2664  0.406746  Wastewater treatment\n\nwaste water treatment ...
2       3687  0.315601  Mechanical heat treatment\n\nMechanical heat t...
3       1161  0.265114  List of solid waste treatment technologies\n\n...
4         83  0.245892  Mechanical biological treatment\n\nA mechanica...

# Parte 2: Recuperación con BM25
### Actividad:

Implementa un sistema de recuperación usando el modelo BM25.
Para el mismo conjunto de 10 queries, verifica la recuperación del sistema

In [ ]:
from rank_bm25 import BM25Okapi
import numpy as np
import pandas as pd

# 1. Tokenizar los documentos preprocesados
tokenized_docs = [doc.split() for doc in processed_docs]

# 2. Crear el modelo BM25
bm25 = BM25Okapi(tokenized_docs)

print("Modelo BM25 creado correctamente.")

Modelo BM25 creado correctamente.

In [ ]:
# 3. Función de búsqueda con BM25
def search_bm25(query, top_k=5):
    # Preprocesar la consulta y convertirla en tokens
    query_tokens = preprocess(query).split()

    # Calcular puntajes de relevancia
    scores = bm25.get_scores(query_tokens)

    # Obtener los índices de los documentos más relevantes
    top_indices = np.argsort(scores)[::-1][:top_k]

    # Construir resultados
    results = []
    for idx in top_indices:
        results.append({
            "documento": int(idx),
            "score": float(scores[idx]),
            "texto": documents[idx][:200]
        })

    return pd.DataFrame(results)

In [16]:
# 4. Probar las mismas 10 consultas
bm25_results = {}

for query in queries:
    print("=" * 80)
    print("QUERY:", query)
    result = search_bm25(query)
    bm25_results[query] = result
    display(result)

================================================================================
QUERY: artificial intelligence

   documento      score                                              texto
0        669  14.292287  Open Letter on Artificial Intelligence\n\nIn J...
1        485  13.857551  Strategic Computing Initiative\n\nThe United S...
2       2618  13.608052  Artificial general intelligence\n\nArtificial ...
3       3799  13.148273  Stochastic neural analog reinforcement calcula...
4       3226  12.238894  Hypothetical technology\n\nHypothetical techno...

================================================================================
QUERY: machine learning

   documento      score                                              texto
0       4733  12.272041  Teaching machine\n\nTeaching machines were ori...
1       3498  11.831675  Sidney L. Pressey\n\nSidney Leavitt Pressey (B...
2        466  11.598824  Information engineering (field)\n\nInformation...
3       1892  10.933898  Data stream mining\n\nData Stream Mining is th...
4       4457  10.876585  GP5 chip\n\nThe GP5 is a co-processor accelera...

================================================================================
QUERY: computer networks

   documento     score                                              texto
0       1616  9.333793  Network literacy\n\nNetwork literacy is an eme...
1       1341  9.057603  Application-oriented networking\n\nApplication...
2        270  8.364441  LIRIC Associates\n\nLIRIC Associates was a com...
3       4009  8.129422  Computing\n\nComputing is any activity that us...
4       3328  7.994890  Frederic Vester\n\nFrederic Vester (November 2...

================================================================================
QUERY: operating systems

   documento     score                                              texto
0       3532  6.607718  List of operating systems\n\nThis is a list of...
1       1687  6.462617  ACM SIGOPS\n\nACM SIGOPS is the Association fo...
2        740  6.305295  Asymmetric multiprocessing\n\nIn an asymmetric...
3       4955  5.840778  Embedded system\n\nAn embedded system is a pro...
4       1970  5.646502  Squirrel Systems\n\nSquirrel Systems is a Burn...

================================================================================
QUERY: database systems

   documento     score                                              texto
0       2577  9.941336  EDA database\n\nAn EDA database is a database ...
1       2060  9.614823  Operational database\n\nOperational database m...
2       2947  9.339284  Polyglot persistence\n\nPolyglot persistence i...
3       2213  9.311238  Open Database Connectivity\n\nIn computing, Op...
4       1700  8.881834  Data warehouse\n\nIn computing, a data warehou...

================================================================================
QUERY: cyber security

   documento      score                                              texto
0       3841  16.054016  Michael Gregg\n\nMichael Gregg is an American ...
1       3431  14.513731  Mr. Robot\n\nMr. Robot is an American drama th...
2       4258  14.190332  Cyber-physical system\n\nA cyber-physical (als...
3       2924  12.881339  Cyber electronic warfare\n\nCyber electronic w...
4       2057  12.142611  Military computers\n\nThis article specificall...

================================================================================
QUERY: probability and statistics

   documento      score                                              texto
0       2296  15.036523  K-distribution\n\nIn probability and statistic...
1       3709  14.627985  Arnold Allen\n\nArnold Oral Allen was an Ameri...
2       3180  12.237241  Cytel\n\nCytel is a multinational statistical ...
3       1591  10.472801  Ballistic conduction in single-walled carbon n...
4        466   9.279343  Information engineering (field)\n\nInformation...

================================================================================
QUERY: software engineering

   documento     score                                              texto
0       1904  8.231163  Institute of Software Engineers\n\nThe Institu...
1        193  8.053967  Software diagnosis\n\nSoftware diagnosis (also...
2       4009  7.972742  Computing\n\nComputing is any activity that us...
3        824  7.905550  Software development\n\nSoftware development i...
4        855  7.902934  Hungarian Testing Board\n\nThe Hungarian Testi...

================================================================================
QUERY: data structures

   documento     score                                              texto
0       3487  8.472344  Ocean data acquisition system\n\nAn ocean data...
1       3635  7.607777  PEARL (programming language)\n\nPEARL, or Proc...
2        407  7.599669  Directed assembly of micro- and nano-structure...
3       4816  7.525688  Integrated computational materials engineering...
4       1892  7.503254  Data stream mining\n\nData Stream Mining is th...

================================================================================
QUERY: java programming

   documento      score                                              texto
0       4473  16.975028  Real time Java\n\nReal time Java is a catch-al...
1       2513  15.331149  Skeleton (computer programming)\n\nSkeleton pr...
2       1023  13.972967  Simon Phipps (programmer)\n\nSimon Phipps is a...
3        722  12.881870  Programmer\n\nA programmer, developer, dev, co...
4       1128  12.739243  Standard Performance Evaluation Corporation\n\...

# Parte 3: Comparación de resultados
### Actividad:

Verifica cuáles documentos son recuperados (y en qué orden) por cada modelo de recuperación

In [17]:
comparison = []

for query in queries:
    tfidf_docs = tfidf_results[query]["documento"].tolist()
    bm25_docs = bm25_results[query]["documento"].tolist()

    comparison.append({
        "query": query,
        "tfidf_top5": tfidf_docs,
        "bm25_top5": bm25_docs,
        "coincidencias": len(set(tfidf_docs) & set(bm25_docs))
    })

comparison_df = pd.DataFrame(comparison)
comparison_df

,query,tfidf_top5,bm25_top5,coincidencias
0,artificial intelligence,"[3905, 4563, 669, 2618, 485]","[669, 485, 2618, 3799, 3226]",3
1,machine learning,"[4733, 51, 466, 3227, 3498]","[4733, 3498, 466, 1892, 4457]",3
2,computer networks,"[15, 4009, 4553, 1341, 2923]","[1616, 1341, 270, 4009, 3328]",2
3,operating systems,"[3532, 4955, 174, 1687, 3578]","[3532, 1687, 740, 4955, 1970]",3
4,database systems,"[1158, 2577, 2963, 2060, 4410]","[2577, 2060, 2947, 2213, 1700]",2
5,cyber security,"[2924, 4258, 699, 3947, 3841]","[3841, 3431, 4258, 2924, 2057]",3
6,probability and statistics,"[3799, 2296, 3709, 3138, 2493]","[2296, 3709, 3180, 1591, 466]",2
7,software engineering,"[4982, 193, 824, 1477, 711]","[1904, 193, 4009, 824, 855]",2
8,data structures,"[1700, 4604, 3616, 521, 1892]","[3487, 3635, 407, 4816, 1892]",1
9,java programming,"[4473, 2169, 613, 465, 2513]","[4473, 2513, 1023, 722, 1128]",2